### ISSUE TITLE
CaffeModel2Json Error on running caffemodel2json.py

### ISSUE THREAD

**Issue by sahil912** [DeepLearningKit/DeepLearningKit#17]
Hi,

I am getting error while converting the caffe model 2 json using caffemodel2json.py

**Command run**:
`python ./caffemodel2json.py caffe-master/src/caffe/proto/caffe.proto bvlc_alexnet.caffemodel > dump.json`

**Error**:

`protobuf: calling protoc
Traceback (most recent call last):
  File "./caffemodel2json.py", line 65, in <module>
    subprocess.check_call(['protoc', '--proto_path', os.path.dirname(args.caffe_proto), '--python_out', args.codegenDir, args.caffe_proto])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

Could you please help with this.
 Thanks

**Comment by TernaK** [comment]
Your problem in on line 65 in caffemodel2json.py which has to do with **protoc**. I had this issue and what fixed it was uninstalling the versions of protobuf I had previously installed. I did a fresh install using macports with the command **port install py27-protobuf**. This will install the right dependencies for python2.7 which is the default python on OSX.
I hope this helps.
